### ISSUE TITLE
calling client.close() does not terminate the client process but causes a reconnect.

### ISSUE THREAD

**Issue by janiversen** [pymodbus-dev/pymodbus#1198]
### Versions

* Python:
* OS:
* Pymodbus:
* Modbus Hardware (if used):

### Pymodbus Specific
* Server: tcp/rtu/ascii - sync/async
* Client: tcp/rtu/ascii - sync/async

### Description

What were you trying, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
# code and logs here.

# please use the following to format logs when posting them here
import pymodbus
pymodbus.pymodbus_apply_logging_config()
```

**Comment by ElTarget** [comment]
This is because the call function is connected by default during the process of sending packets
![image](https://user-images.githubusercontent.com/41426791/212445745-28195c18-3958-4c56-a058-954b7d7b26a5.png)

**Comment by janiversen** [comment]
Of course the client is connected when sending packets, this is done so to ensure an automatic reconnect if the server closes the connection. However the problem described is different, when the app calls client.close() it should not continue.

**Comment by janiversen** [comment]
I assume you are aware that the line you point out, is NOT an actual tcp/ip connect(), but it a method in our classes.

**Comment by ElTarget** [comment]
For example, if we call the read_coils() function, it will enter the transaction.py file, as long as we have a configuration client, then calling read_coils(), is to try to connect once, both to judge the connectivity and to connect. So I will judge client.socket before using it, this object exists in our different clients.
![image](https://user-images.githubusercontent.com/41426791/212462301-515b58c0-871c-4fc6-abe8-bef9d59b2f5e.png)
![image](https://user-images.githubusercontent.com/41426791/212462405-a34899a1-6c00-4415-aa75-59daffd36dca.png)

**Comment by janiversen** [comment]
You have lost me, I am not really sure what your idea are. BUT Pull requests are welcome and then we can review the suggested changes.

is_socket_open() is in serial.py not the general for all types, and it is because for serial we need to know if the communication is open (which is NOT the same as being connected).

**Comment by ElTarget** [comment]
Well.. I'm just giving an example. Because we use functions that will enter the transaction.py. I think this is why we manually client.close() and then use something like "read_coils()" to execute.
![image](https://user-images.githubusercontent.com/41426791/212463197-85a79960-a5e2-44d2-837e-a1ffd6a12c47.png)

**Comment by janiversen** [comment]
The app (not pymodbus) uses client.close() when it wants to terminate the client, and continue doing other things, so the app expects the client to close connection and communication. The app will not do any more client calls.

The current version does however reconnects to the server after a delay instead of keeping it closed. The workaround at the moment is to do
```
   client.close()
   del client
```
but that is not a good solution.
