### ISSUE TITLE
REPL client Remove `unit` argument

### ISSUE THREAD

**Issue by dhoomakethu** [pymodbus-dev/pymodbus#1258]
### Versions

* Python:
* OS:
* Pymodbus:
* Modbus Hardware (if used):

### Pymodbus Specific
* Server: tcp/rtu/ascii - NA
* Client: tcp/rtu/ascii - REPL tcp

### Description

Run REPL client to interact with modbus server

### Code and Logs

<img width="561" alt="image" src="https://user-images.githubusercontent.com/9276974/212352120-db97d9ec-feba-4a55-a72b-bf82bf383745.png">

<img width="576" alt="image" src="https://user-images.githubusercontent.com/9276974/212352174-51b45a43-ac93-49ac-9682-1e041b8d0c8e.png">

**Comment by janiversen** [comment]
I think that also affects the json data being passed.
