### ISSUE TITLE
Docker publish fails on dev.

### ISSUE THREAD

**Issue by janiversen** [pymodbus-dev/pymodbus#1259]
I have tried to restart the job, but it continues to fail.

**Comment by janiversen** [comment]
@dhoomakethu do you mind taking a look at this ?

**Comment by dhoomakethu** [comment]
Will check later today. Thanks

**Comment by janiversen** [comment]
just fyi, I just updated another PR, and docker publish worked there...no idea why

**Comment by janiversen** [comment]
The problem is the key of the certificate.

And on top of that there are a lot of warnings about methods being outdated and will be removed soon. 

Have you used an old skeleton ? I searched for examples and ours seems very complicated compared to what I saw, but I am just observing, since I do not have experience with docker.

**Comment by janiversen** [comment]
@1261 did not solve the problem.

**Comment by janiversen** [comment]
My comment was wrong, I was looking at the wrong examples, sorry about that.

But we still have a key problem.
