### ISSUE TITLE
async serial server isn't explicitly started by StartAsyncSerialServer

### ISSUE THREAD

**Issue by alexrudd2** [pymodbus-dev/pymodbus#1280]
Now my python modbus server isn't replying to the client talking to it on the serial port. It was working with 3.1.0, it fails with 3.1.1, and it's not because of the logging changes. I'll investigate...

Meanwhile, found a typo:
tcp.py line 213:
`            if self.params.host.startswith("unit:"):`

"unit" should be "unix", since it's about unix sockets...

===

I found the issue, it works now.

In 3.1.0, StartAsyncSerialServer() calls server.start()
In 3.1.1 it does not and returns the server object.

So I added .start() in my code on the return value of StartAsyncSerialServer(), and now the server serves.

I wonder if this is a bug in my code, perhaps I was supposed to call .start(), but it feels weird that a function called StartAsyncSerialServer() does not actually start the server. Hmm...

_Originally posted by @peufeu2 in https://github.com/pymodbus-dev/pymodbus/issues/1279#issuecomment-1400424302_

**Comment by alexrudd2** [comment]
The call to `start.()` was indeed removed in [`925660`](https://github.com/pymodbus-dev/pymodbus/pull/1256/files#diff-2b868d687ff9a33d19e875a6454786b499fb360e483cd5fa94bbd826198eb7deL1153).

**Comment by janiversen** [comment]
hmmm seems like a real bug. Pull requests are welcome.
