### ISSUE TITLE
ServerStop

### ISSUE THREAD

**Issue by HamishSwanbarton** [pymodbus-dev/pymodbus#1297]
### Versions

* Python: 3.10
* OS: Windows 11
* Pymodbus: 3.1.1
* Modbus Hardware (if used): None

### Pymodbus Specific
* Server: tcp - sync
* Client: NA

### Description
I was trying to run multiple Modbus servers, and shut them down cleanly. However only one of the modbus servers gets shut down, the rest continue running. I expected the threads the servers were running in to stop, but all but one of them are still active.

### Code and Logs
This is my test that fails - an assertion error gets raised on the last line.
```python
import threading
import time
from pymodbus.server import StartTcpServer, ServerStop

import pymodbus

pymodbus.pymodbus_apply_logging_config()

n = 2
# Create n servers in threads
for i in range(n):
    thread2 = threading.Thread(target=StartTcpServer, kwargs={'context': None, 'address': ('127.0.0.1', 5020 + i)})
    thread2.start()

time.sleep(1)
assert threading.active_count() == n + 1
for _ in range(n):
    ServerStop()

time.sleep(1)
assert threading.active_count() == 1
```
Logs:
```
C:\Users\Hamish\Git\site-simulator\.venv310\Scripts\python.exe C:\Users\Hamish\Git\site-simulator\tests\wip.py 
Traceback (most recent call last):
  File "C:\Users\Hamish\Git\site-simulator\tests\wip.py", line 22, in <module>
    assert threading.active_count() == 1
AssertionError
```
I am able to get this test to pass, by adding a line to `ServerStop`, shown here:
```python
def ServerStop():  # pylint: disable=invalid-name
    """Terminate server."""
    if my_job := _serverList.get_server():
        if my_job.loop.is_running():
            asyncio.run_coroutine_threadsafe(my_job.async_await_stop(), my_job.loop)
            sleep(0.1)
            _serverList._remove(my_job)  # <---- This line causes test to pass
    else:
        raise RuntimeError("ServerStop called without server task active.")
```
My guess is that without the added line, `ServerStop` is closing the first server, but then the second time `ServerStop` is called, it seems to try to stop the already stopped server. Adding the `_serverList._remove(my_job)` line was an attempt to stop this, and make subsequent `ServerStop` calls stop the servers we want them to stop. I could have made this a PR, but I am not sure on ServerStop's intended behaviour, so I've left this as an issue for now.

Let me know if you'd like any more information.

**Comment by janiversen** [comment]
You start the threads so you need to stop the threads, it is not in the hands of pymodbus.

Running multiple synchronous server is really asking for trouble. ServerStop() should always close the server on top of the list, what you have added should happen in my_job.async_await_stop(), but it seems to have been dropped.

Feel  free to make a pull request with your change.

**Comment by janiversen** [comment]
I am actually impressed that it works at all, it was never intended to, nor tested to run multiple synchronous servers.

**Comment by HamishSwanbarton** [comment]
Ah, thanks that is quite helpful. I shall restructure my code instead.
