### ISSUE TITLE
PyModbus 3.1.2 Dependency Issues

### ISSUE THREAD

**Issue by bmehr2000** [pymodbus-dev/pymodbus#1332]
### Versions

* Python: **3.9.5**
* OS: **Windows 10**
* Pymodbus: **3.1.2**
* Modbus Hardware (if used): **N/A**

### Pymodbus Specific
* Server: **tcp - sync**
* Client: **tcp - sync**

### Description

I installed the recent 3.1.2 release and on the initial execution of the program, I got an error about the "redis" module not being found. I installed "redis" and tried again, then got "sqlalchemy" module not found.

I was under the impression that Pymodbus didn't need other dependencies installed, other than PySerial.

I tested with PyModbus 3.0.2 and code functioned as expected.

### Code and Logs

```python
# code and logs here.

# please use the following to format logs when posting them here
from pymodbus.server import (
    StartTcpServer
)

def run_server():
    print("Run")
    print("Server")

# Name Check
if __name__ == "__main__":
    run_server()
```

**Comment by janiversen** [comment]
Sorry about that, this is a known error in 3.1.2 and it is solved on dev. I will try to see if I can get time to make 3.1.3 today.
