### ISSUE TITLE
[docs bug] ModbusClientMixin.write_register docstring incorrect terminology

### ISSUE THREAD

**Issue by jamesbraza** [pymodbus-dev/pymodbus#1349]
### Versions

* Python: 3.10.9
* OS: macOS Monterey version 12.6
* Pymodbus: 3.1.1
* Modbus Hardware (if used): n/a

### Pymodbus Specific
* Server: n/a
* Client: tcp sync

### Description

For [`ModbusClientMixin.write_register`](https://pymodbus.readthedocs.io/en/v3.1.3/source/library/client.html#pymodbus.client.mixin.ModbusClientMixin.write_register), why is the address referencing reads in the docstring?

When I look at [`WriteSingleRegisterRequest`](https://pymodbus.readthedocs.io/en/v3.1.3/source/library/pymodbus.html#pymodbus.register_write_message.WriteSingleRegisterRequest), it's referencing writes, so I think `write_register`s docstring is incorrect.

### Code and Logs

```python
    def write_register(
        self, address: int, value: Union[int, float, str], slave: int = 0, **kwargs: any
    ) -> pdu_req_write.WriteSingleRegisterResponse:
        """Write register (code 0x06).

        :param address: Start address to read from
        ...
        """

class WriteSingleRegisterRequest(ModbusRequest):
    ...

    def __init__(self, address=None, value=None, unit=None, **kwargs):
        """Initialize a new instance.

        :param address: The address to start writing add
        ...
        """
```

**Comment by janiversen** [comment]
pull requests are welcome
