### ISSUE TITLE
[docs improvement] Unused _thread_lock in performance module example

### ISSUE THREAD

**Issue by jamesbraza** [pymodbus-dev/pymodbus#1393]
### Description

The below code is dead in the [performance module example](https://pymodbus.readthedocs.io/en/v3.1.3/source/examples.html#performance-module) ([this line](https://github.com/pymodbus-dev/pymodbus/blob/v3.1.3/examples/v2.5.3/performance.py#L34)):

```python
_thread_lock = Lock()
```

I think this line should be either:
- Removed: if unused and irrelevant
- Inline commented: if unused but relevant
- Used to protect client access

### Additional Context

For what it's worth, this was also mentioned here: https://github.com/pymodbus-dev/pymodbus/discussions/1269#discussion-4759551

**Comment by jamesbraza** [comment]
What happened is I searched the docs for `Thread`, and it's one of the few results.  I didn't realize that `2.5.3` examples are sort of just reference material at this point.

Just for posterity, https://github.com/pymodbus-dev/pymodbus/issues/1394 is related.

**Comment by janiversen** [comment]
No problem, I named them 2.5.3, to indicate that they belong to that release.

Help in updating them is very appreciated, just submit a pull request.
