### ISSUE TITLE
specify Modbus NaN values

### ISSUE THREAD

**Issue by joanwa** [pymodbus-dev/pymodbus#1460]
### Versions

- Python: 3.10
- OS: macOS
- Pymodbus: 3.2.2
- Modbus Hardware (if used): Any SMA Inverter

### Pymodbus Specific

- Server: tcp
- Client: tcp

### Description
I'm using modbus to read data from an PV inverter. Over night that inverter goes into sleep mode and only returns their declared NaN values, which becomes +/-2,147,483,648 +/-(2^32)/2 for an int32 value, depending on the register read.
The inverters manufacturer, SMA, provides a table with their NaN values (screenshot below).

It would be great if we could have an optional parameter to specify its expected NaN return value. This would save a lot of conditionals to show 'NaN' or 0 instead of the returned +/-2,147,483,648.

<img width="617" alt="sma_modbus_nan" src="https://user-images.githubusercontent.com/7691102/227958483-c87d7047-4aab-4d2e-9829-3e65f1812e40.png">

I'm wondering if this an valid feature request, or if this is seen as some manufacturer does what it wants to return weird values for weird states.

**Comment by janiversen** [comment]
This is not really something pymodbus cares about, it returns registers each 16bit and not values like float etc.

We do have convert functions, but I am not sure how such a change would fit. I think you would actually need a value filter to get rid of extreme small or extreme large values (The modbus integration in homeassistant uses filters).

Having said that, pull requests are welcome if you want a change.

**Comment by janiversen** [comment]
@joanwa did you solve your problem ? (I can see you opened a PR in HomeAssistant, is it because this is not a pymodbus problem ?)

**Comment by janiversen** [comment]
Closing this issue as not a problem in pymodbus.

**Comment by joanwa** [comment]
Yes exactly, can be solved in home assistant, not a pymodbus issue! Thanks!
