### ISSUE TITLE
Evaluate using HomeAssistant rules in ruff

### ISSUE THREAD

**Issue by alexrudd2** [pymodbus-dev/pymodbus#1477]
> If it makes things simpler then please make a PR that changes from bandit to flake8-bandit.
> 
> Can you please ( if you have not already) the rules from HA, commented out, that way it is easier to activate when you find t8mr.

_Originally posted by @janiversen in https://github.com/pymodbus-dev/pymodbus/issues/1476#issuecomment-1500557392_

https://github.com/home-assistant/core/blob/7eccef87c2cccb834f5ff394f765e697831390e3/pyproject.toml#L240

- [ ] "B007", # Loop control variable {name} not used within loop body
- [ ] "B014", # Exception handler with duplicate exception
- [x] "C",  # complexity
- [x] "D",  # docstrings
- [x] "E",  # pycodestyle
- [x] "F",  # pyflakes/autoflake
- ~~"ICN001", # import concentions; {name} should be imported as {asname}~~
- [x] "PGH004",  # Use specific rule codes when using noqa
- [x] "PLC0414", # Useless import alias. Import alias does not rename original package.
- [x] "SIM105", # Use contextlib.suppress({exception}) instead of try-except-pass
- [x] "SIM117", # Merge with-statements that use the same scope
- [x] "SIM118", # Use {key} in {dict} instead of {key} in {dict}.keys()
- [x] "SIM201", # Use {left} != {right} instead of not {left} == {right}
- [x] "SIM212", # Use {a} if {a} else {b} instead of {b} if not {a} else {a}
- [x] "SIM300", # Yoda conditions. Use 'age == 42' instead of '42 == age'.
- [x] "SIM401", # Use get from dict with default instead of an if block
- ~~"T20",  # flake8-print~~
- [ ] "TRY004", # Prefer TypeError exception for invalid type
- [x] "RUF006", # Store a reference to the return value of asyncio.create_task
- [x] "UP",  # pyupgrade
- [x] "W",  # pycodestyle

ignore = [

- [x] "D202",  # No blank lines allowed after function docstring
- ~~"D203",  # 1 blank line required before class docstring~~
- ~~"D213",  # Multi-line docstring summary should start at the second line~~
- ~~"D406",  # Section name should end with a newline~~
- ~~"D407",  # Section name underlining~~
- [x] "E501",  # line too long
- [x] "E731",  # do not assign a lambda expression, use a def
Ignored due to performance: https://github.com/charliermarsh/ruff/issues/2923
- ~~"UP038", # Use `X | Y` in `isinstance` call instead of `(X, Y)`~~

**Comment by janiversen** [comment]
I did not express myself well, please add these rules in our ruff.toml but comment those out that currently gives you a headache.

This PR is clean and nice, let's keep it like that, and then you can un comment the rules in new PR(s).

**Comment by alexrudd2** [comment]
> I did not express myself well, please add these rules in our ruff.toml but comment those out that currently gives you a headache.

I understood you, but remember better if it's an issue assigned to me.  (I work across a dozen projects)

**Comment by janiversen** [comment]
Ahh it is a new one, sorry I am on my iPAD this evening.

**Comment by janiversen** [comment]
Looking forward to see more PR around this theme. 

I too work on a number of projects and I have absolutely no problem with you opening issues as reminders.

**Comment by alexrudd2** [comment]
See #1480 and #1481

**Comment by janiversen** [comment]
Looks like you have the version active ? or am I missing something?

**Comment by alexrudd2** [comment]
> Looks like you have the version active ? or am I missing something?

I don't understand your question.


===

Anyways, I've gone and deleted some rules where I don't see value (such as `flake8-print`), and enabled a few more easy ones.

There are three remaining "big" rulesets which I think are useful, but require more substantial work.  I've put them in but commented out.
- bandit
- Tryceratops
- McCabe complexity

**Comment by janiversen** [comment]
we already use bandit directly and mccabe via pylint, so it puzzles me why those 2 are big jobs....the third one is new to me.

Anyhow if you want we can divide them, or you do it slowly when you have time.

**Comment by alexrudd2** [comment]
> Bandit is used:
> 

o_0. OK, I missed that.  Hopefully https://github.com/pymodbus-dev/pymodbus/pull/1488 makes it clearer (and kills another CI runner, yay)

However, `ruff` still doesn't actually have full parity with `flake8-bandit` so I think it's best to wait a bit.  (https://github.com/charliermarsh/ruff/issues/1646)


> Reducing [the McCabe complexity] is a nice goal, but please please do it very carefully, and in chunks I can review....I have already tried and failed (or at least postponed).

Agreed, it's difficult!
![image](https://user-images.githubusercontent.com/52292902/231262634-3482ae6d-7dea-4dee-86ad-bb6e857a8bd1.png)

**Comment by janiversen** [comment]
I believe you do !

**Comment by janiversen** [comment]
I just read about ruff, in another project. Is rule M001 default ? if not we should activate it, to get warnings when there are unused noga statements.

**Comment by alexrudd2** [comment]
Hmm, it appears `M001` has been remapped to `RUF100`. This would be part of the `RUF` rules, which are not enabled by default, BUT are enabled for pymodbus [here](https://github.com/pymodbus-dev/pymodbus/blob/dev/ruff.toml#L28).

I'd suggest moving the other project from `M001` to `RUF100` if they haven't already.

**Comment by janiversen** [comment]
thanks.

**Comment by alexrudd2** [comment]
> > we already use bandit directly and mccabe via pylint, so it puzzles me why those 2 are big jobs....the third one is new to me.
> 
> For McCabe/pylint, I intend to actually reduce the complexity and not just use `pylint: ignore` :)

If https://github.com/pymodbus-dev/pymodbus/pull/1510 is OK, we're down to two functions with a McCabe complexity of > 10.

> pymodbus/transaction.py:127:9: C901 `execute` is too complex (23 > 10)
> pymodbus/transaction.py:335:9: C901 `_recv` is too complex (19 > 10)

Note that both of them have large `if/else if/else` blocks that are functionally switch statements.  If 
https://github.com/charliermarsh/ruff/issues/3597 gets implemented that will reduce their scores.

**Comment by janiversen** [comment]
I have reworked many if/else constructs to
if - return...and no else. I try in general not to have nested if/else.

So I suggest you follow the same pattern if possible.

**Comment by alexrudd2** [comment]
> I have reworked many if/else constructs to if - return...and no else. I try in general not to have nested if/else.
> 
> So I suggest you follow the same pattern if possible.

Yes, it's good advice when possible for _nested_ if/else.  However, I meant code like this (sequential if / else if / else) that would be a switch/case or match in other languages:
https://github.com/pymodbus-dev/pymodbus/blob/759b222869f5da4ce26d2d18be826bf258ed7a0e/pymodbus/transaction.py#L340-L349

Actually, since there are now only a few left I think I will just ignore them, switch to ruff, and disable the pylint McCabe.

**Comment by janiversen** [comment]
Switch to ruff sounds like a good idea, but please do not disable McCabe, but add "pylint: disable=complex..." or whatever it is called in ruff, for those couple of methods.

**Comment by alexrudd2** [comment]
> Switch to ruff sounds like a good idea, but please do not disable McCabe, but add "pylint: disable=complex..." or whatever it is called in ruff, for those couple of methods.

I meant disabling the _pylint_ McCade while enabling it in ruff.  https://github.com/pymodbus-dev/pymodbus/pull/1510/commits/a25de7fad942b921a0715949d09488795b4a7692
