### ISSUE TITLE
Why is the read_coils return value not a ReadCoilsResponse object?

### ISSUE THREAD

**Issue by lui305** [pymodbus-dev/pymodbus#1478]
### Versions

- Python:3.9.13
- OS:windows
- Pymodbus:3.2.2

### Pymodbus Specific

- Server: tcp
- Client: tcp

### Description
Hi!
When I am alone read_coils function, the return value for “ReadDiscreteInputsResponse (24)”, when I use write_coil functions first, then use read_coils function, Its return value changes to “WriteCoilResponse(100) => True”. Shouldn't the return value of the read_coils function be the ReadCoilsResponse object?
### Code and Logs

```python
code one:
###################
from pymodbus.client import ModbusTcpClient
# 连接到Modbus服务器
client = ModbusTcpClient('169.254.94.2', port=502)
client.connect()
# client.write_coil(100,True,1)
a=client.read_coils(100,1)
print(a)
# close the connection
client.close()
#################
print (a) is " ReadDiscreteInputsResponse (24)"
#################

code two:
###################
from pymodbus.client import ModbusTcpClient
# 连接到Modbus服务器
client = ModbusTcpClient('169.254.94.2', port=502)
client.connect()
client.write_coil(100,True,1)
a=client.read_coils(100,1)
print(a)
# close the connection
client.close()
#################
print (a) is " WriteCoilResponse(100) => True"
#################

**Comment by janiversen** [comment]
I am not sure what problem you have, but pymodbus works as expected, please see the example I added.
