### ISSUE TITLE
Evaluate  flake8-pytest-style as a linter

### ISSUE THREAD

**Issue by alexrudd2** [pymodbus-dev/pymodbus#1500]
> @janiversen I would recommend checking out [`flake8-pytest-style`](https://github.com/m-burst/flake8-pytest-style), you can hook it right into `pre-commit`.
> 
> It really helps one best adopt `pytest`'s DSL

@jamesbraza 
If you are still interested, it's fast and easy to enable in ruff.
https://beta.ruff.rs/docs/rules/#flake8-pytest-style-pt

Personally on my other projects it only found `PT001` and `PT018`.  I found those to be useless and kept it disabled.

```
examples/client_calls.py:213:5: PT018 [*] Assertion should be broken down into multiple parts
examples/client_calls.py:218:5: PT018 [*] Assertion should be broken down into multiple parts
test/test_client.py:41:5: PT006 [*] Wrong name(s) type in `@pytest.mark.parametrize`, expected `tuple`
test/test_client.py:209:5: PT006 [*] Wrong name(s) type in `@pytest.mark.parametrize`, expected `tuple`
test/test_client.py:364:2: PT023 [*] Use `@pytest.mark.skip()` over `@pytest.mark.skip`
test/test_client.py:543:5: PT006 [*] Wrong name(s) type in `@pytest.mark.parametrize`, expected `tuple`
test/test_client_multidrop.py:18:5: PT005 Fixture `_framer` returns a value, remove leading underscore
test/test_client_multidrop.py:23:5: PT005 Fixture `_callback` returns a value, remove leading underscore
test/test_example_client_server.py:77:26: PT006 [*] Wrong name(s) type in `@pytest.mark.parametrize`, expected `tuple`
test/test_example_client_server.py:105:26: PT006 [*] Wrong name(s) type in `@pytest.mark.parametrize`, expected `tuple`
test/test_exceptions.py:30:17: PT017 Found assertion on exception `exc` in `except` block, use `pytest.raises()` instead
test/test_factory.py:99:5: PT004 Fixture `setup` does not return anything, add leading underscore
test/test_framers.py:19:2: PT001 [*] Use `@pytest.fixture()` over `@pytest.fixture`
test/test_framers.py:25:2: PT001 [*] Use `@pytest.fixture()` over `@pytest.fixture`
test/test_logging.py:31:9: PT006 [*] Wrong name(s) type in `@pytest.mark.parametrize`, expected `tuple`
test/test_server_asyncio.py:108:5: PT004 Fixture `setup_teardown` does not return anything, add leading underscore
test/test_server_task.py:152:9: PT015 Assertion always fails, replace with `pytest.fail()`
test/test_server_task.py:152:9: PT017 Found assertion on exception `exc` in `except` block, use `pytest.raises()` instead
test/test_server_task.py:250:13: PT015 Assertion always fails, replace with `pytest.fail()`
test/test_server_task.py:273:9: PT015 Assertion always fails, replace with `pytest.fail()`
test/test_server_task.py:273:9: PT017 Found assertion on exception `exc` in `except` block, use `pytest.raises()` instead
test/test_server_task.py:348:13: PT015 Assertion always fails, replace with `pytest.fail()`
test/test_simulator.py:407:9: PT006 [*] Wrong name(s) type in `@pytest.mark.parametrize`, expected `tuple`
test/test_unix_socket.py:48:28: PT019 Fixture `_mock_run_server` without value is injected as parameter, use `@pytest.mark.usefixtures` instead
test/test_unix_socket.py:55:46: PT019 Fixture `_mock_run_server` without value is injected as parameter, use `@pytest.mark.usefixtures` instead
Found 25 errors.
```

_Originally posted by @alexrudd2 in https://github.com/pymodbus-dev/pymodbus/issues/1428#issuecomment-1513208052_

**Comment by alexrudd2** [comment]
> I would not like to run pytest with every commit that is far too slow.  
> Feel free to make a PR with the above mentioned PTxxx.


_Originally posted by @janiversen in https://github.com/pymodbus-dev/pymodbus/issues/1428#issuecomment-1513259939_

@jamesbraza's suggestion was not to run pytest itself, but `flake8-pytest-style`, which is flake8 plugin that only cares about unit tests.  It can be run in `ruff` (and therefore pre-commit) by enabling the `PT` rules.  (which wasn't possible at the time he posted)

**Comment by jamesbraza** [comment]
Oh nice, glad to see `ruff` here!  Yeah `ruff` is actually how I originally discovered `flake8-pytest-style`.

As of `v1.7.2` I think multiple of the checks were valuable, `PT019` has a known bug, and some of the checks were overly pedantic (agree with you).  I think that overall it definitely is a value add.

I also appreciate `pylint`'s `redefined-outer-name`'s synergy with `pytest.fixture`. From the [`pytest.fixture` docs](https://docs.pytest.org/en/stable/reference/reference.html#pytest-fixture): 

>  a fixture is used in the same module in which it is defined, the function name of the fixture will be shadowed by the function arg that requests the fixture; one way to resolve this is to name the decorated function `fixture_<fixturename>` and then use `@pytest.fixture(name='<fixturename>')`.

`pylint` docs on this: https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/redefined-outer-name.html

```python
@pytest.fixture()
def rtu_framer():  # pylint: disable=redefined-outer-name
    """RTU framer."""

# Move from ^^^ to vvv

@pytest.fixture(name="rtu_framer")
def rtu_framer_fixture():  # Or fixture_rtu_framer
    """RTU framer."""
```

I recommend incorporating that rename as well.

**Comment by janiversen** [comment]
@alexrudd2 I am open for integration in our precommit, after I understood, that it is running the tests, but style checking them).

You are in the driver seat and decides what goes in. We do quite a number of "redefined_outer_name" which was needed to avoid other problems, but there might be other solutions.

**Comment by alexrudd2** [comment]
@jamesbraza Would you be interested in submitting a PR?  You appear more knowledgeable than I.  (my own unit tests are... a work in progress)

**Comment by janiversen** [comment]
would be nice to get the tests corrected. It is an easy job.
