### ISSUE TITLE
minval and maxval for float32 in simulator

### ISSUE THREAD

**Issue by RyIot3329** [pymodbus-dev/pymodbus#1658]
### Versions

- Python: Python 3.9.2
- OS: Debian 11
- Pymodbus: dev

### Pymodbus Specific

- Server: tcp - Simulator

### Description

I have this defined in my json file for the simulator.

        {
          "addr": [7, 8],
          "value": 72.0,
          "action": "random",
          "kwargs": { "minval": 65.0, "maxval": 78.0 }
        }

It does not seem to follow the minval and maxval values from what I can see. I am getting random Float values, so that works. But it isn't in between the bounds. Any ideas?

**Comment by janiversen** [comment]
Which version are you using ? that might be the problem.

**Comment by janiversen** [comment]
datastore/simulator.py#633 it seems to do what it is supposed to do.

I need to check it.

**Comment by janiversen** [comment]
I see it's not covered in our test suite, I will add a specific test and see what happens.

**Comment by janiversen** [comment]
I have now added a test case, and as far as I can see everything works as it should.

Did you make the configuration within the "float32" label ?

**Comment by RyIot3329** [comment]
Yeah I added it within the "float" block. Would it help to upload the entire json file?

**Comment by janiversen** [comment]
No, a debug log would help.

**Comment by RyIot3329** [comment]
Sorry for the delay on this. Here is the log file and the JSON file I am using
[log.txt](https://github.com/pymodbus-dev/pymodbus/files/12072540/log.txt)
[tstat.txt](https://github.com/pymodbus-dev/pymodbus/files/12072544/tstat.txt)
