### ISSUE TITLE
Out of Date 'version.py' File Is Present in PyPI Package

### ISSUE THREAD

**Issue by helsmore** [pymodbus-dev/pymodbus#1703]
### Versions

- Python: 3.9.2
- OS: Deban 11/Bullseye
- Pymodbus: 3.4.0
- Modbus Hardware (if used): N/A

### Pymodbus Specific

- Server: N/A
- Client: N/A

### Description

When installing Pymodbus from PyPI an out-of-date file, `version.py`, from a previous release (3.2.2) is included in the package installation:
1. Install Pymodbus with `sudo pip3 install pymodbus`, in my case the installation is to `/usr/local/lib/python3.9/dist-packages/pymodbus/`.
2. Version in `/usr/local/lib/python3.9/dist-packages/pymodbus/__init__.py` defined as `3.4.0` (as expected)
3. Version in `/usr/local/lib/python3.9/dist-packages/pymodbus/version.py` defined as `3.2.2` (I think this file shouldn't exist)

I downloaded `pymodbus-3.4.0-py3-none-any.whl` from PyPI and unpacked it to check the contents, the stray `version.py` exists in the package, but doesn't seem to be in the Pymodbus Git repo, so I assume it's getting included accidentally from the machine where the package is built.

### Code and Logs

N/A

**Comment by janiversen** [comment]
Thanks I think it comes from a not deleted build environment, I am right now preparing 3.4.1 and will check it.

**Comment by janiversen** [comment]
V3.4.1 should not have version.py in PyPI (at least I cannot see it).
