### ISSUE TITLE
discrete inputs

### ISSUE THREAD

**Issue by AWilson10** [pymodbus-dev/pymodbus#1726]
This isnt a bug but more a question. For the modbus server how do I update the discrete inputs for the client to read them.
I want to take the hardware Input values from my controller and update the databank (i presume) in some way so client gets the value.
Thanks in advance

**Comment by janiversen** [comment]
Since this is not a bug, please open a question in "discussions".

Look at our examples, one of them is an updating server.

**Comment by AWilson10** [comment]
Thanks

**Comment by AWilson10** [comment]
Not a bug
