### ISSUE TITLE
Should `constants.Endian` be an enum?

### ISSUE THREAD

**Issue by Booplicate** [pymodbus-dev/pymodbus#1741]
### Versions

- Python: 3.11
- OS: Arch
- Pymodbus: 3.4.1

### Pymodbus Specific

- Server: tcp/rtu/ascii - all
- Client: tcp/rtu/ascii - all

### Description

I think it'd be more convenient if `Endian` was an actual enum, could help with type safety. For compatibility it could be made "str enum" and be fully compatible with literals.

All target python versions have support for enums.

If desired, I could work on this.

**Comment by janiversen** [comment]
feel free to submit a pull request.

From the top of my head I see no reason why it cannot be an enum.
