### ISSUE TITLE
Fault with config

### ISSUE THREAD

**Issue by cyberpater84** [pymodbus-dev/pymodbus#1806]
### Versions

- Python: 3.11
- OS: 2023.10.1
- Pymodbus: 3.5.2
- Modbus Hardware (if used): Ecoforest

### Pymodbus Specific

- Server: tcp/rtu/ascii - sync/async
- Client: tcp/rtu/ascii - sync/async

### Description

When I use this integration I get a fault with reboot of the configuration YAML

### Code and Logs

Logger:` homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:226
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 08:33:41 (3 occurrences)
Last logged: 15:24:21

[139874146179904] The system cannot restart because the configuration is not valid: Component error: modbus - cannot import name 'ModbusBaseClient' from 'pymodbus.client' (/usr/local/lib/python3.11/site-packages/pymodbus/client/__init__.py)
[139874142896960] The system cannot restart because the configuration is not valid: Component error: modbus - cannot import name 'ModbusBaseClient' from 'pymodbus.client' (/usr/local/lib/python3.11/site-packages/pymodbus/client/__init__.py)
[139874139856704] The system cannot restart because the configuration is not valid: Component error: modbus - cannot import name 'ModbusBaseClient' from 'pymodbus.client' (/usr/local/lib/python3.11/site-packages/pymodbus/client/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 599, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Component error: modbus - cannot import name 'ModbusBaseClient' from 'pymodbus.client' (/usr/local/lib/python3.11/site-packages/pymodbus/client/__init__.py)

`
modbus:
  - name: "ecoforest"
    type: rtuovertcp
    host: IP_ADDRESS
    port: 502
    binary_sensors:
    - name: heatpump_alarm
      slave: 17
      address: 50
    - name: Heatpump Summer
      slave: 17
      address: 127
    - name: Heatpump Winter
      slave: 17
      address: 128
    sensors:
    - name: Heatpump Buitentemperatuur
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 11
      data_type: int16
    - name: Heatpump Boiler
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 8
      data_type: int16
    - name: Heatpump Pressure Brine
      unit_of_measurement: Bar
      scale: 0.1
      precision: 1
      slave: 17
      address: 13
      data_type: int16
    - name: Heatpump Pressure Heating
      unit_of_measurement: Bar
      scale: 0.1
      precision: 1
      slave: 17
      address: 14
      data_type: int16
    - name: Heatpump Brine air outlet
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 29
      data_type: int16
    - name: Heatpump Brine out
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 1
      data_type: int16
    - name: Heatpump Brine in
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 2
      data_type: int16
    - name: Heatpump Heating out
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 3
      data_type: int16
    - name: Heatpump Heating in
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 4
      data_type: int16
    - name: Heatpump Compressor suction temperature
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 5
      data_type: int16
    - name: Heatpump Compresor suction pressure
      unit_of_measurement: Bar
      scale: 0.1
      precision: 1
      slave: 17
      address: 6
      data_type: int16
    - name: Heatpump Compressor discharge pressure
      unit_of_measurement: Bar
      scale: 0.1
      precision: 1
      slave: 17
      address: 7
      data_type: int16
    - name: Heatpump Condensation temperature
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 94
      data_type: int16

    - name: Heatpump Superheat
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 132
      data_type: int16
    - name: Heatpump Expansion valve position
      unit_of_measurement: "%"
      slave: 17
      address: 133
      data_type: int16

    - name: Heatpump Supply Temperature SG2
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 194
      data_type: int16
    - name: Heatpump Supply Temperature SG3
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 195
      data_type: int16
    - name: Heatpump Supply Temperature SG4
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 196
      data_type: int16
      
    - name: Heatpump Start Temperature DHW
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 198
      data_type: int16

    - name: Heatpump Evaporation temperature
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 199
      data_type: int16
    - name: Heatpump Compressor discharge temperature
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 203
      data_type: int16
    - name: Heatpump COP
      unit_of_measurement: COP
      scale: 0.1
      precision: 1
      slave: 17
      address: 30
      data_type: int16
    - name: Heatpump EER
      unit_of_measurement: EER
      scale: 0.1
      precision: 1
      slave: 17
      address: 202
      data_type: int16

    - name: Heatpump Compressor RPM
      unit_of_measurement: RPM
      slave: 17
      address: 5002
      data_type: int16
    - name: Heatpump Scroll temperature
      unit_of_measurement: °C
      slave: 17
      address: 5004
      data_type: int16
    - name: Heatpump Inverter temperature
      unit_of_measurement: °C
      slave: 17
      address: 5005
      data_type: int16
      
    - name: Heatpump Working Hours L
      slave: 17
      address: 5080
      data_type: int16
    - name: Heatpump Working Hours H
      slave: 17
      address: 5081
      data_type: int16

    - name: Heatpump Powerconsumption
      unit_of_measurement: W
      slave: 17
      address: 5082
      data_type: int16
    - name: Heatpump Condensation capacity
      unit_of_measurement: W
      slave: 17
      address: 5083
      data_type: int16
    - name: Heatpump Evaporation capacity
      unit_of_measurement: W
      slave: 17
      address: 5185
      data_type: int16
      
    - name: Heatpump Condensation Energy january
      unit_of_measurement: kWh
      slave: 17
      address: 5144
      data_type: int16
    - name: Heatpump Condensation Energy february
      unit_of_measurement: kWh
      slave: 17
      address: 5145
      data_type: int16
    - name: Heatpump Condensation Energy march
      unit_of_measurement: kWh
      slave: 17
      address: 5146
      data_type: int16
    - name: Heatpump Condensation Energy april
      unit_of_measurement: kWh
      slave: 17
      address: 5147
      data_type: int16
    - name: Heatpump Condensation Energy may
      unit_of_measurement: kWh
      slave: 17
      address: 5148
      data_type: int16
    - name: Heatpump Condensation Energy june
      unit_of_measurement: kWh
      slave: 17
      address: 5149
      data_type: int16
    - name: Heatpump Condensation Energy july
      unit_of_measurement: kWh
      slave: 17
      address: 5150
      data_type: int16
    - name: Heatpump Condensation Energy august
      unit_of_measurement: kWh
      slave: 17
      address: 5151
      data_type: int16
    - name: Heatpump Condensation Energy september
      unit_of_measurement: kWh
      slave: 17
      address: 5152
      data_type: int16
    - name: Heatpump Condensation Energy october
      unit_of_measurement: kWh
      slave: 17
      address: 5153
      data_type: int16
    - name: Heatpump Condensation Energy november
      unit_of_measurement: kWh
      slave: 17
      address: 5154
      data_type: int16
    - name: Heatpump Condensation Energy december
      unit_of_measurement: kWh
      slave: 17
      address: 5155
      data_type: int16

    - name: Heatpump Evaporation Energy january
      unit_of_measurement: kWh
      slave: 17
      address: 5156
      data_type: int16
    - name: Heatpump Evaporation Energy february
      unit_of_measurement: kWh
      slave: 17
      address: 5157
      data_type: int16
    - name: Heatpump Evaporation Energy march
      unit_of_measurement: kWh
      slave: 17
      address: 5158
      data_type: int16
    - name: Heatpump Evaporation Energy april
      unit_of_measurement: kWh
      slave: 17
      address: 5159
      data_type: int16
    - name: Heatpump Evaporation Energy may
      unit_of_measurement: kWh
      slave: 17
      address: 5160
      data_type: int16
    - name: Heatpump Evaporation Energy june
      unit_of_measurement: kWh
      slave: 17
      address: 5161
      data_type: int16
    - name: Heatpump Evaporation Energy july
      unit_of_measurement: kWh
      slave: 17
      address: 5162
      data_type: int16
    - name: Heatpump Evaporation Energy august
      unit_of_measurement: kWh
      slave: 17
      address: 5163
      data_type: int16
    - name: Heatpump Evaporation Energy september
      unit_of_measurement: kWh
      slave: 17
      address: 5164
      data_type: int16
    - name: Heatpump Evaporation Energy october
      unit_of_measurement: kWh
      slave: 17
      address: 5165
      data_type: int16
    - name: Heatpump Evaporation Energy november
      unit_of_measurement: kWh
      slave: 17
      address: 5166
      data_type: int16
    - name: Heatpump Evaporation Energy december
      unit_of_measurement: kWh
      slave: 17
      address: 5167
      data_type: int16

    - name: Heatpump Electrical Consumption january
      unit_of_measurement: kWh
      slave: 17
      address: 5168
      data_type: int16
    - name: Heatpump Electrical Consumption february
      unit_of_measurement: kWh
      slave: 17
      address: 5169
      data_type: int16
    - name: Heatpump Electrical Consumption march
      unit_of_measurement: kWh
      slave: 17
      address: 5170
      data_type: int16
    - name: Heatpump Electrical Consumption april
      unit_of_measurement: kWh
      slave: 17
      address: 5171
      data_type: int16
    - name: Heatpump Electrical Consumption may
      unit_of_measurement: kWh
      slave: 17
      address: 5172
      data_type: int16
    - name: Heatpump Electrical Consumption june
      unit_of_measurement: kWh
      slave: 17
      address: 5173
      data_type: int16
    - name: Heatpump Electrical Consumption july
      unit_of_measurement: kWh
      slave: 17
      address: 5174
      data_type: int16
    - name: Heatpump Electrical Consumption august
      unit_of_measurement: kWh
      slave: 17
      address: 5175
      data_type: int16
    - name: Heatpump Electrical Consumption september
      unit_of_measurement: kWh
      slave: 17
      address: 5176
      data_type: int16
    - name: Heatpump Electrical Consumption october
      unit_of_measurement: kWh
      slave: 17
      address: 5177
      data_type: int16
    - name: Heatpump Electrical Consumption november
      unit_of_measurement: kWh
      slave: 17
      address: 5178
      data_type: int16
    - name: Heatpump Electrical Consumption december
      unit_of_measurement: kWh
      slave: 17
      address: 5179
      data_type: int16

    - name: Heatpump Number Of Starts L
      slave: 17
      address: 5281
      data_type: int16
    - name: Heatpump Number Of Starts H
      slave: 17
      address: 5282
      data_type: int16
`

**Comment by janiversen** [comment]
This is the pymodbus project, not the homeassistant project ! pymodbus does not use configuration.yaml

But from personal experience I can tell you that you have a faulty homeassistant installation, seems it never installed the modbus component.

OR you have a custom component that conflicts with the modbus component.

**Comment by cyberpater84** [comment]
You are right there is a modbus component that conflicting, it is this one https://github.com/wimb0/home-assistant-saj-modbus
After a uninstall of this applications the main modbus is working properly
