### ISSUE TITLE
Error module

### ISSUE THREAD

**Issue by CarlosGomezPerea** [pymodbus-dev/pymodbus#1848]
Hello, I don't know what happen, I'll try , change python version, ask IA ,etc...but always the same problems. Only with module, another programs differents module, its workin ok.

[Running] python -u "c:\Users\carlo\Desktop\Programas Python\Programas\modbus1.py"
Traceback (most recent call last):
  File "c:\Users\carlo\Desktop\Programas Python\Programas\modbus1.py", line 1, in <module>
    from pymodbus.client.sync import ModbusTcpClient
ModuleNotFoundError: No module named 'pymodbus.client.sync'

[Done] exited with code=1 in 0.95 seconds

thanks

### Versions

- Python:
- OS:
- Pymodbus:
- Modbus Hardware (if used):

### Pymodbus Specific

- Server: tcp/rtu/ascii - sync/async
- Client: tcp/rtu/ascii - sync/async

### Code and Logs

```python
# code and logs here.

# please use the following to format logs when posting them here
import pymodbus

pymodbus.pymodbus_apply_logging_config()
```

**Comment by janiversen** [comment]
Your code is for an old version of pymodbus, please read the documentation and update your program.
