### ISSUE TITLE
Extra and Constant Section is Missing

### ISSUE THREAD

**Issue by ArAhmedRaza** [pymodbus-dev/pymodbus#1868]
I have not found Extra and Constant in this Documentation https://pymodbus.readthedocs.io/en/latest/. I think these Sections are missing.

**Comment by janiversen** [comment]
We have rewrapped the documentation in v3.5.4, so that the documentation is more user facing. Constants and Extra was not really something applications should use so it was cut from the main bar, but is still in "pymodbus internals".
