### ISSUE TITLE
Change prof directory to be in build.

### ISSUE THREAD

**Issue by janiversen** [pymodbus-dev/pymodbus#2002]
### Versions

- Python:
- OS:
- Pymodbus:
- Modbus Hardware (if used):

### Pymodbus Specific

- Server: tcp/rtu/ascii - sync/async
- Client: tcp/rtu/ascii - sync/async

### Code and Logs

```python
# code and logs here.

# please use the following to format logs when posting them here
import pymodbus

pymodbus.pymodbus_apply_logging_config("DEBUG")
```

**Comment by janiversen** [comment]
@alexrudd2 do you have experience with pytest-profiling ?? I want to configure the output directory, but google do not give me any hints on how to do it.

Help is very much needed :-)

**Comment by alexrudd2** [comment]
No, sorry.

**Comment by janiversen** [comment]
Not possible...prof is hardcoded.
