### ISSUE TITLE
 REPL argument completions don't work

### ISSUE THREAD

**Issue by alexrudd2** [pymodbus-dev/pymodbus#2008]
File "/home/alex/.local/lib/python3.10/site-packages/pymodbus/repl/client/completer.py", line 133, in get_completions
    commands = list(command.get_completion())

Exception 'NoneType' object has no attribute 'get_completion'
Press ENTER to continue...

### Versions

- Python: 3.10
- OS: Ubuntu (WSL 2)
- Pymodbus: `3.6.4`
- Modbus Hardware (if used):

### Pymodbus Specific

REPL completions don't work.  After hitting ENTER it is possible to continue typing 1 character at a time.

**Comment by alexrudd2** [comment]
I will likely fix this with the `pyright` checks (if it isn't already fixed in `dev`)

**Comment by alexrudd2** [comment]
The command completions work fine, it's only the argument completions that have the issue,

**Comment by janiversen** [comment]
REPL is moved, so closing.
