### ISSUE TITLE
Add uint64 & other 64bit support in Device Entries in Modbus Simulator

### ISSUE THREAD

**Issue by schwarzkunstlerin** [pymodbus-dev/pymodbus#2027]
Why there is no support in configuration for uint64 in Device Entries in Modbus Simulator? I think there should be one and we should be able to initialize this type of data stored in the simulator's register, especially since the library supports reading and writing uint64.

I'm currently working on simulating a device with u64int registers, using the JSON config and I really miss the types!

**Comment by janiversen** [comment]
Very simple, because nobody programmed it.

Pull requests are welcome.

**Comment by schwarzkunstlerin** [comment]
I am not sure if I will be able to write something sensible on this topic in the near future, because I don't fully understand how pymodbus and the simulator work yet, but if someone would do it in their free time, I'd be very grateful.

**Comment by schwarzkunstlerin** [comment]
Well, I started to understand better Modbus & pymodbus. I forked the repo, maybe I will be able to add something sensible as a contribution to this issue. Staaaay tuned!

**Comment by janiversen** [comment]
Seems there are no interest in this issue (although it seems relevant)
