### ISSUE TITLE
ModbusException 0x07 is missing in pdu.py

### ISSUE THREAD

**Issue by doelki** [pymodbus-dev/pymodbus#2063]
In pdu.py is ModbusException NegativeAcknowledge missing. Is it possible to add: NegativeAcknowledge  = 0x07 ?

class ModbusExceptions:  

    IllegalFunction = 0x01
    IllegalAddress = 0x02
    IllegalValue = 0x03
    SlaveFailure = 0x04
    Acknowledge = 0x05
    SlaveBusy = 0x06
    MemoryParityError = 0x08
    GatewayPathUnavailable = 0x0A
    GatewayNoResponse = 0x0B

**Comment by janiversen** [comment]
Pull requests are welcome.
