### ISSUE TITLE
Retrieve server timestamp

### ISSUE THREAD

**Issue by shamyjun22** [pymodbus-dev/pymodbus#2167]
### Versions

- Python: 3.11
- OS: Windows
- Pymodbus: 3.6.4
- Modbus Hardware (if used): 

### Pymodbus Specific

- Server: Kepware KEPServer
- Client: tcp- async

### Description
I had already made a successful connection with the Kepware KEPServer and read values from holding registers.
My question is, is it possible to get the timestamp from the server?

**Comment by janiversen** [comment]
That depends on whether or not the server makes it available as a register.

Apart from that it is hard to know which timestamp you want, but anyhow please read the server manual, or file an issue with that project...it does not seem to have anything to do with pymodbus,

**Comment by shamyjun22** [comment]
Thanks for you reply. I have read the manual. It seems that Kepware doesn't support date type register addressing. I can now generate datetime, but the problem is it in string format. It is possible for pymodbus to handle string data type?

**Comment by janiversen** [comment]
Pymodbus handles registers, what you do with the data is up to you.

**Comment by shamyjun22** [comment]
> Pymodbus handles registers, what you do with the data is up to you.

Thanks. It is clear to me now.
