### ISSUE TITLE
No response received from remote while modpoll is able to get it

### ISSUE THREAD

**Issue by sciunto** [pymodbus-dev/pymodbus#2233]
Hi,

### Versions

- Python: 3.12.4
- OS: archlinux
- Pymodbus: 3.6.9
- Modbus Hardware (if used): arduino rev4 wifi

### Description

I'm able to get data with modpoll (see command and log below), which tends to tell me that my hardware is fine.
The code is uploaded on an arduino uno rev 4, USBC cable. A dummy potentiometer is connected to the pin A3.

### Code and Logs

The code on arduino is

```C
#include <ModbusRTUSlave.h>


ModbusRTUSlave modbus_slave(Serial);
const uint8_t slaveID = 1;
const uint32_t baud = 9600;

uint16_t holdingRegisters[20] = {0};

int sensor;

void setup() {
    modbus_slave.configureHoldingRegisters(holdingRegisters, 20);
    modbus_slave.begin(slaveID, baud, SERIAL_8N1);
}

void loop() {
    sensor = analogRead(A3);

    holdingRegisters[0] = sensor;
    modbus_slave.poll();
    delay(100);
}
```

I can retrieve the data with

```sh
modpoll -m rtu -a 1 -r 1 -c 10 -b 9600 -p none /dev/ttyACM0
```

output:

```
modpoll 3.11 - FieldTalk(tm) Modbus(R) Master Simulator
Copyright (c) 2002-2024 proconX Pty Ltd
Visit https://www.modbusdriver.com for Modbus libraries and tools.

Protocol configuration: Modbus RTU, FC3
Slave configuration...: address = 1, start reference = 1, count = 10
Communication.........: /dev/ttyACM0, 9600, 8, 1, none, t/o 1.00 s, poll rate 1000 ms
Data type.............: 16-bit register, output (holding) register table

-- Polling slave... (Ctrl-C to stop)
[1]: 875
[2]: 0
[3]: 0
[4]: 0
[5]: 0
[6]: 0
[7]: 0
[8]: 0
[9]: 0
[10]: 0
-- Polling slave... (Ctrl-C to stop)
[1]: 875
[2]: 0
[3]: 0
[4]: 0
[5]: 0
[6]: 0
[7]: 0
[8]: 0
[9]: 0
[10]: 0
-- Polling slave... (Ctrl-C to stop)
```

Now, if i try with pymodbus

```python

#!/usr/bin/env python
import pymodbus
from pymodbus.client import ModbusSerialClient as ModbusClient
import time

pymodbus.pymodbus_apply_logging_config()


def main():
    client = ModbusClient(
        method='rtu',
        port='/dev/ttyACM0',
        baudrate=9600,
        parity='N',
        stopbits=1,
        bytesize=8,
        timeout=1
    )

    if client.connect():
        print('connected')
        result = client.read_holding_registers(address=1, count=10, unit=1)
        print(result)
        result = client.read_holding_registers(address=1, count=10, unit=1)
        print(result)
    else:
        print("Unable to connect to the Modbus server")



if __name__ == "__main__":
    main()

```

I have

```
connected
2024-07-17 09:16:31,062 DEBUG logging:103 Current transaction state - IDLE
2024-07-17 09:16:31,062 DEBUG logging:103 Running transaction 1
2024-07-17 09:16:31,062 DEBUG logging:103 SEND: 0x0 0x3 0x0 0x1 0x0 0xa 0x95 0xdc
2024-07-17 09:16:31,062 DEBUG logging:103 Resetting frame - Current Frame in buffer - 
2024-07-17 09:16:31,062 DEBUG logging:103 New Transaction state "SENDING"
2024-07-17 09:16:31,063 DEBUG logging:103 Changing transaction state from "SENDING" to "WAITING FOR REPLY"
2024-07-17 09:16:33,104 DEBUG logging:103 Transaction failed. (Modbus Error: [Invalid Message] No response received, expected at least 4 bytes (0 received)) 
2024-07-17 09:16:33,104 DEBUG logging:103 Processing: 
2024-07-17 09:16:33,104 DEBUG logging:103 Getting transaction 0
2024-07-17 09:16:33,104 DEBUG logging:103 Changing transaction state from "PROCESSING REPLY" to "TRANSACTION_COMPLETE"
Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 4 bytes (0 received)
2024-07-17 09:16:33,106 DEBUG logging:103 Current transaction state - TRANSACTION_COMPLETE
2024-07-17 09:16:33,106 DEBUG logging:103 Running transaction 2
2024-07-17 09:16:33,106 DEBUG logging:103 SEND: 0x0 0x3 0x0 0x1 0x0 0xa 0x95 0xdc
2024-07-17 09:16:33,106 DEBUG logging:103 Resetting frame - Current Frame in buffer - 
2024-07-17 09:16:33,107 DEBUG logging:103 Changing state to IDLE - Last Frame End - None Current Time stamp - 1721200593.106943
2024-07-17 09:16:33,110 DEBUG logging:103 New Transaction state "SENDING"
2024-07-17 09:16:33,111 DEBUG logging:103 Changing transaction state from "SENDING" to "WAITING FOR REPLY"
2024-07-17 09:16:35,114 DEBUG logging:103 No response received, Expected 25 bytes Received 0 bytes !!!!
2024-07-17 09:16:35,114 DEBUG logging:103 Changing transaction state from "WAITING FOR REPLY" to "PROCESSING REPLY"
2024-07-17 09:16:35,115 DEBUG logging:103 RECV: 
2024-07-17 09:16:35,115 DEBUG logging:103 Processing: 
2024-07-17 09:16:35,115 DEBUG logging:103 Getting transaction 0
2024-07-17 09:16:35,152 DEBUG logging:103 Changing transaction state from "PROCESSING REPLY" to "TRANSACTION_COMPLETE"
Modbus Error: [Input/Output] No Response received from the remote slave/Unable to decode response
```

Thank you for your assistance.

**Comment by sciunto** [comment]
Looks like unit has been changed to slave... and many people are struggling with the change of API

**Comment by sciunto** [comment]
The fixed code is:

```python
import pymodbus
from pymodbus.client import ModbusSerialClient as ModbusClient
import time

pymodbus.pymodbus_apply_logging_config()


def main():
    client = ModbusClient(
        method='rtu',
        port='/dev/ttyACM0',
        baudrate=9600,
        parity='N',
        stopbits=1,
        bytesize=8,
        timeout=1
    )

    if client.connect():
        print('connected')
        result = client.read_holding_registers(address=0, count=10, slave=1)
        print(result)
        for r in result.registers:
            print(r)
    else:
        print("Unable to connect to the Modbus server")



if __name__ == "__main__":
    main()

```
Hopefully, it will help someone.

**Comment by janiversen** [comment]
Well your pymodbus code is using an unknown parameter so clearly it gets no response.

please read the documentation for v3.6.9 and correct your code.

**Comment by sciunto** [comment]
I read the documentation before posting, looked for examples on the web, etc. I think I spent more than 3-4 hours to get some that works, because I checked everything in the stack. Even one of the example in the doc seamed outdated to me. It's after an additional hour that I detect an API change that my eye didn't catch, and the bug tracker indicates that this is not just me.

I believe that a good API must:
* be strict against incorrect parameters, ie crash if wrong. Here the problem is catching all the kwarg.
* put in place a deprecation cycle  when a parameter is changed over 2-3 versions: old and new API must be usable. Warn the user when the old API is used. Specify when the compatibility will be removed.
* Avoid as much as possible API changes.

This is very important for projects that is widely used as this one.

Thanks for your work
Best

**Comment by janiversen** [comment]
If that is your opinion then do something about it, do not expect others to do what you want.

All our examples are tested with each merge and extra with each release, so they work...but very obvious you read documentation and examples from an old version.

**Comment by janiversen** [comment]
We see a lot of user like yourself, that prefers spending hours using examples from google and non official documentation.

Would it not be so much easier to read the official documentation and use the corresponding examples....

**Comment by sciunto** [comment]
Please, don't be rude.

> If that is your opinion then do something about it, do not expect others to do what you want.

This is the role of the project manager/core dev to adopt policies.

> Would it not be so much easier to read the official documentation and use the corresponding examples....

Could not find a nice tutorial to step in. Sorry. And again, believe me or not, I read your doc and could not find the problem easily.

**Comment by sciunto** [comment]
> All our examples are tested with each merge and extra with each release, so they work...but very obvious you read documentation and examples from an old version.

I considered this : https://pymodbus.readthedocs.io/en/latest/source/examples.html#client-performance-sync-vs-async
Tagged as v:latest.

```sh
mktmpenv
pip install 'pymodbus[all]' 
```

I just tried to make the first import of your example.

```sh
python
Python 3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymodbus import FramerType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'FramerType' from 'pymodbus' (/home/fr/.local
/share/virtualenvs/tmp-d9923135ae11b63/lib/python3.12/site-packages/pymodbus/
__init__.py)

>>> import pymodbus
>>> 
```

Then, I stopped reading the examples.

**Comment by janiversen** [comment]
> Please, don't be rude.
> 
> 
> 
> > If that is your opinion then do something about it, do not expect others to do what you want.
> 
> 
> 
> This is the role of the project manager/core dev to adopt policies.

No, this is open source, if you want something changed, you are responsible.

Contributors to a project, mostly do so, because they have a problem.

> 
> Could not find a nice tutorial to step in. Sorry. And again, believe me or not, I read your doc and could not find the problem easily.

Not sure what document you read, we provide simple ready to go examples for beginners as well as more advanced examples...they are documented as such, in the examples.

Apart from that our client headers include a short tutorial on how to use the client...so I honestly do not know what more you want.

**Comment by janiversen** [comment]
> > All our examples are tested with each merge and extra with each release, so they work...but very obvious you read documentation and examples from an old version.
> 
> 
> 
> I considered this : https://pymodbus.readthedocs.io/en/latest/source/examples.html#client-performance-sync-vs-async
> 
> Tagged as v:latest.
> 
> 
> 
> ```sh
> 
> mktmpenv
> 
> pip install 'pymodbus[all]' 
> 
> ```
> 
> 
> 
> I just tried to make the first import of your example.
> 
> 
> 
> ```sh
> 
> python
> 
> Python 3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417] on linux
> 
> Type "help", "copyright", "credits" or "license" for more information.
> 
> >>> from pymodbus import FramerType
> 
> Traceback (most recent call last):
> 
>   File "<stdin>", line 1, in <module>
> 
> ImportError: cannot import name 'FramerType' from 'pymodbus' (/home/fr/.local
> 
> /share/virtualenvs/tmp-d9923135ae11b63/lib/python3.12/site-packages/pymodbus/
> 
> __init__.py)
> 
> 
> 
> >>> import pymodbus
> 
> >>> 
> 
> ```
> 
> 
> 
> Then, I stopped reading the examples.

That error is because you did not install pymodbus v3.6.9 !

Apart from that, since you found the examples, starting with the simple_* would have been simpler (however you still need to ensure you have the correct version installed).

**Comment by janiversen** [comment]
Did you remember to activate your temp venv, that could very well be the problem.

**Comment by sciunto** [comment]
I'm in the venv. activated automatically by my tool.

Version check:
```python
>>> pymodbus.__version__
'3.6.9'

```

**Comment by sciunto** [comment]
> No, this is open source, if you want something changed, you are responsible.
I start to understand why there are so many API changes then. If anyone can pull in any direction... :(

**Comment by sciunto** [comment]
I unsubscribe from the thread, obviously, you don't want to hear the users, you are not ready to accept that there might be issues not coming from the newcomers.
