### ISSUE TITLE
Add issue tracker / source code repository to the doc

### ISSUE THREAD

**Issue by sciunto** [pymodbus-dev/pymodbus#2234]
Hi,

It would be useful for users to have a link to the code repository and the issue tracker in the documentation.

Thanks

**Comment by janiversen** [comment]
We do have both:

https://pymodbus.readthedocs.io/en/latest/source/readme.html

we point to our github repository, what do you want more ?

**Comment by sciunto** [comment]
In the menu to be visible. 

I searched for tracker in the doc and could not find anything. See https://pymodbus.readthedocs.io/en/latest/search.html?q=tracker&check_keywords=yes&area=default
Same for bug: https://pymodbus.readthedocs.io/en/latest/search.html?q=bug&check_keywords=yes&area=default#

**Comment by janiversen** [comment]
Pull requests are welcome.

**Comment by janiversen** [comment]
"tracker" and "bug" are  not the names most commonly used in open source. Since GitHub uses "issues" so the vast majority of open source follow that.
