### ISSUE TITLE
Server and client decoders handle exceptions differently

### ISSUE THREAD

**Issue by alexrudd2** [pymodbus-dev/pymodbus#2259]
`ServerDecoder`
https://github.com/pymodbus-dev/pymodbus/blob/1b2cb7eb6651c2cb9ec0eb8323e645b0758fc26b/pymodbus/factory.py#L92-L102

`ClientDecoder`
https://github.com/pymodbus-dev/pymodbus/blob/1b2cb7eb6651c2cb9ec0eb8323e645b0758fc26b/pymodbus/factory.py#L229-L241

The generic `except Exception` was added a long time ago in [`1.5.0`](https://github.com/pymodbus-dev/pymodbus/pull/294/files#diff-09a427404023a7916a4afacf2ff25eac10b00120218a033b4f866ab778076850)

It doesn't seem right to have them differ; which is preferred?

**Comment by janiversen** [comment]
you are right, the first one is better (without the generic exception).
