### ISSUE TITLE
Type Hint for write_registers value parameter wrong?

### ISSUE THREAD

**Issue by rauberdaniel** [pymodbus-dev/pymodbus#2308]
`BinaryPayloadBuilder.build(…)` returns `list[bytes]`
```python
def build(self) -> list[bytes]:
```
but `ModbusTcpClient.write_registers(…)` expects `list[int]` as values argument
```python
def write_registers(self, address: int, values: list[int], slave: int = 1, skip_encode: bool = False) -> T:
``` 

According to my tests, write_registers however actually expects `list[bytes]` so I think this type hint there is wrong? Can anybody confirm or deny that?

**Comment by janiversen** [comment]
I will take a look.

**Comment by janiversen** [comment]
You are right it should be list[bytes], while write_register expects an int.

You are welcome to make a pull request if you want, otherwise I will correct it when I get around to it,
.
