### ISSUE TITLE
Start/stop multiple servers

### ISSUE THREAD

**Issue by VDigitall** [pymodbus-dev/pymodbus#2341]
### Description

It would be highly beneficial to have the ability to start and stop multiple servers simultaneously within the pymodbus library. I saw that implementation but it was removed two years ago.

It would be good to have the possibility:
- Start a few servers
- Stop all servers at once.
- Stop each server separately

**Comment by janiversen** [comment]
You can actually already do that by making a simple function....have a look at how start*server works and collects and array of active servers.

Pull requests are always welcome if you want changes.
