### ISSUE TITLE
ModbusServerRequestHandler connection objects are not removed from parent server.active_connections when connection closed or lost

### ISSUE THREAD

**Issue by JimWiesler** [pymodbus-dev/pymodbus#2454]
### Versions

- Python: 3.12.5
- OS: macOS Sequoia 15.1
- Pymodbus: 3.7.4, problem started on 3.7.3 with change [2338](https://github.com/pymodbus-dev/pymodbus/pull/2338/commits/1b72c6401ccb0a227e7675d81a0931dc14e44835)
- Modbus Hardware (if used): N/A

### Pymodbus Specific

- Server: tcp async
- Client: tcp async

### Description
Monitoring the active connections (`ModbusServerRequestHandler->ModbusProtocol` objects) of a server object (`ModbusTcpServer->ModbusBaseServer->ModbusProtocol`) via the server's `.active_connections` dict object.  <mark>Connection objects in the dict are no longer `popped` out of the `.active_connections` dict when the connection closes.</mark>

In change [2338](https://github.com/pymodbus-dev/pymodbus/pull/2338/commits/1b72c6401ccb0a227e7675d81a0931dc14e44835) all new `ModbusServerRequestHandler` objects set their `.is_server` attribute to `True`, even though `ModbusServerRequestHandler` is a "Protocol Handler" not a "Server Implementation".

This behavior breaks the `transport.py` `ModbusProtocol.__close` method of the `ModbusServerRequestHandler` by `return`ing prior to the `if self.listener:` section where the `ModbusServerRequestHandler` is popped from the server's `.active_connections` attribute:

<pre><code>
    def __close(self, reconnect: bool = False) -> None:
        """Close connection (internal).
        :param reconnect: (default false), try to reconnect
        """
        if self.transport:
            self.transport.close()
            self.transport = None  # type: ignore[assignment]
        self.recv_buffer = b""
        <mark>if self.is_server:</mark>
            for _key, value in self.active_connections.items():
                value.listener = None
                value.callback_disconnected(None)
                value.close()
            self.active_connections = {}
            <mark>return</mark>
        if not reconnect and self.reconnect_task:
            self.reconnect_task.cancel()
            self.reconnect_task = None
            self.reconnect_delay_current = 0.0
        if self.listener:
            <mark>self.listener.active_connections.pop(self.unique_id)</mark>
</code></pre>
A couple extra thoughts:
- Change [2338](https://github.com/pymodbus-dev/pymodbus/pull/2338/commits/1b72c6401ccb0a227e7675d81a0931dc14e44835) seems to me to be a bug, as `ModbusServerRequestHandler` is a Protocol Handler not a Server Implementation (as defined in file `async_io.py` comments).  If I understand the code correctly, `ModbusServerRequestHandler` is an object representing a connected client and should not be treated as a server.
- I was surprised this issue was not flagged by automated test `test/transport/test_comm.py-->test_connected_multiple` - this test seems to cover the same scenario where a connection is closed and the number of `active_connections` is asserted to have decreased from 2 to 1 (`line 241`).

### Code and Logs

<pre><code># Code to reproduce error:
import asyncio

from pymodbus import server as pmbs
from pymodbus.datastore import (
    ModbusSequentialDataBlock,
    ModbusServerContext,
    ModbusSlaveContext
)
from pymodbus.client import AsyncModbusTcpClient

server_port = 10502
server_ip = "127.0.0.1"
store = ModbusSlaveContext(   # Initialize 9999 16-bit values to 32000
    di=ModbusSequentialDataBlock(0, [32000]*9999),
    co=ModbusSequentialDataBlock(0, [32000]*9999),
    hr=ModbusSequentialDataBlock(0, [32000]*9999),
    ir=ModbusSequentialDataBlock(0, [32000]*9999)
)
context = ModbusServerContext(slaves=store, single=True)

async def main():
    server = pmbs.ModbusTcpServer(context=context, address=("0.0.0.0", server_port))
    client1 = AsyncModbusTcpClient(host=server_ip, port=server_port)
    client2 = AsyncModbusTcpClient(host=server_ip, port=server_port)

    # server_wrapper = Server_test()
    # server_run_task = asyncio.create_task(server_wrapper.run())
    await server.listen()
    await asyncio.sleep(0.5)
    print(f"Server started. Expected active_connections = 0, active_connections = {len(server.active_connections)}")

    await client1.connect()
    await asyncio.sleep(0.5)
    print(f"Client 1 started.  Expected active_connections = 1, active_connections = {len(server.active_connections)}")

    await client2.connect()
    await asyncio.sleep(0.5)
    print(f"Client 2 started. Expected active_connections = 2, active_connections = {len(server.active_connections)}")

    client1.close()
    await asyncio.sleep(0.5)
    print(f"Client 1 stopped.  Expected active_connections = 1,  active_connections = {len(server.active_connections)}")

    server.close()
    await asyncio.sleep(0.5)
    print(f"Server stopped.  Expected active_connections = 0,  active_connections = {len(server.active_connections)}")

if __name__ == "__main__":
    asyncio.run(main())
</code></pre>

### Output:
<pre><code>
Server started. Expected active_connections = 0, active_connections = 0
Client 1 started.  Expected active_connections = 1, active_connections = 1
Client 2 started. Expected active_connections = 2, active_connections = 2
<mark>Client 1 stopped.  Expected active_connections = 1,  active_connections = 2</mark>
Server stopped.  Expected active_connections = 0,  active_connections = 0
</code></pre>

**Comment by janiversen** [comment]
Please explain what the problem is, before explaining what the cause is. What is the problem in the app ?

The is_server is needed in all server objects, among others it is used to determine if a request or a response is to be expected.

Pull requests are welcome.
