### ISSUE TITLE
Wierd logic when handling no_response_device in transaction.py

### ISSUE THREAD

**Issue by alexanderK1987** [pymodbus-dev/pymodbus#492]
file: `transaction.py`
function: `def execute(self, request)`

if the comment section in function `def _transact(...)` is correct
the value of `full` parameter for a irresponsive device should be `False` and the value for a responsive device should be `True`.

**Comment by janiversen** [comment]
Are you suggesting to change the comment or the code ? It seems the code works or do you have another opinion ?

**Comment by janiversen** [comment]
Closing as solved (or lack of comment).
